Repository ElzabeEls/ASE_2024_GROUP_B, pull requests merged in 2024-12, with the labels that each got.

#409 Create and store shopping lists ##349
  app/api/shoppingList/route.js
  package-lock.json
  package.json
Labels: Shopping List Backend

#410 402 fix the homejs
  Public/background.jpg
  app/Home.js
  tailwind.config.js
Labels: Recommended Recipes Frontend

#411 Log out route to clear user session #208
  app/api/authorisation/logout/route.js
  middleware.js
Labels: Backend sign-up & sign-in

#412 11 no matching recipes
  app/components/SearchBar.js
  app/recipe/page.js
  lib/utils.js
Labels: Text search

#400 328 voice command repeat step
  app/components/ReadInstructionsButton.js
  app/components/SearchBar.js
  app/recipes/[id]/page.js
  package-lock.json
Labels: Voice AI

#415 feat: add API endpoint to fetch recent recipes sorted by creation date
  app/api/recipes/recent/route.js
Labels: Backend Sorting

#417 11 no matching recipes
  app/components/SearchBar.js
Labels: Text search

#416 Dynamic UI updates #211
  Public/ArejengLogo.png
  Public/ArejengLogoDark.png
  app/Home.js
  app/components/AdvancedFiltering.js
  app/components/Header.js
  app/components/ThemeToggle.js
  app/global.css
  app/layout.js
  app/login/page.js
  app/signup/page.js
  package-lock.json
  tailwind.config.js
Labels: Theme Toggle

#418 Code to exclude image types added to middleware.
  middleware.js
Labels: Backend sign-up & sign-in

#420 Middleware fixes to stop blocking images
  middleware.js
Labels: Backend sign-up & sign-in

#419 Calculate Average Rating for Recipes #246
  app/api/reviews/[recipeId]/route.js
  app/api/reviews/route.js
  app/components/RecipeReviews.js
  lib/calculatingAverageRating.js
Labels: Reviews Frontend, Reviews Backend

#421 Updated login route to set additional cookies for user state and refa…
  app/api/authorisation/login/route.js
  app/api/authorisation/session/route.js
  app/layout.js
Labels: Frontend sign-up & sign-in

#424 218 backend route to add recipe to favourites
  app/api/favourites/route.js
  app/components/FavouriteButton.js
  app/components/Favourites.js
  app/components/Header.js
  app/components/RecipeCard.js
  app/favourites/page.js
  app/recipe/page.js
  lib/api.js
  lib/dummyData/sampleData.js
  package-lock.json
  package.json
Labels: Favouriting Frontend, Favouriting Backend

#425 Recipe details
  app/components/PrepTimeIcon.js
  app/components/ReadInstructionsButton.js
  app/components/RecipeReviews.js
  app/components/SpeedAdjuster.js
  app/global.css
  app/recipe/page.js
  app/recipes/[id]/page.js
  lib/utils.js
Labels: Recipe Details

#426 Log out option #198
  app/components/Header.js
  app/loading.js
Labels: Frontend sign-up & sign-in

#422 Add review and rating for recipe ##227
  app/api/shoppingList/route.js
  app/components/RecipeReviews.js
  middleware.js
Labels: Reviews Frontend
